### PR TITLE
Fix #1565: CSP compliance with plugin templates (don't trigger inline JS and CSS rules)

### LINKED ISSUE #1565: Should Comply to Allow CSP policies (actually this forces the use of unsafe-inline)
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of bootstrap-fileinput.
- [x] This is not an usage question. I confirm having read the plugin [documentation](http://plugins.krajee.com/file-input) and [demos](http://plugins.krajee.com/file-input/demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Set CSP policies to disallow inline (« style-src »)

This is a general issue. It would be necessary to rework things.
There is no quick workaround as I see it.

It should use CSSOM ( $(element).css('prop', value)) 
https://stackoverflow.com/a/29089970/4355295

The actual system is a tree of templates to display things with a replace function to set values.

The solution would be loaded items with no style attr, and then set them using CSSOM.

I have identified 3 entries to fix there :+1:

 - tZoomCache  ( style="display:none" ), easy to fix using a class like ```d-none```
 - tProgress  style="width"  to  set the progress width
 -

    return tmplt.setTokens({
        'previewId': id,
        'caption': caption,
        'title': title,
        'alt': alt,
        'frameClass': css,
        'type': self._getFileType(ftype),
        'fileindex': ind,
        'fileid': fileId || '',
        'typeCss': typeCss,
        'footer': footer,
        'data': d,
        'template': templ || cat,
        'style': styleAttribs ? 'style="' + styleAttribs + '"' : ''
    });

   This last one need to be investigated.
   I could try to propose a PR if this interests you, and if you are not planning a rewrite of this lib   actually.

  I crossed this issue working on my project.

Capture d’écran de 2020-05-27 12-55-58

These are relevant CSP HTTP headers I am using
	
    Content-Security-Policy: default-src 'self' 'nonce-apwNAzO8atqpImT5'; script-src 'unsafe-eval' 'nonce-apwNAzO8atqpImT5'; frame-src 'self' https://docs.google.com; style-src 'nonce-apwNAzO8atqpImT5'; object-src 'none'; base-uri 'none'; report-uri /omenfilemanager/csp/report

### PR DESCRIPTION
**Pull request by Kwaadpepper**
## Scope
This pull request includes a

- [x] Bug fix
- [ ] New feature
- [ ] Translation

## Changes
The following changes were made

- add uniqId method, generates unid ID hash (base 36) using random and DateTime (to avoid collisions)
- add parseEvent method, is an alternative to the evil Eval function, is used to "eval" inline events of templates
- add cspBuffer "class"
    It will store attributes to prevent Dom from parsing them and triggering CSP policies
    It contains 2 methods:
      - parse, will store inline CSS and inline JS events to apply them later using CSSOM and JS event bind
      - apply, will apply inline CSS and inline JS stored previously
    To find where to apply things, it uses the temp attribute "cspTMP" containing a unique ID.

  Please note that I found not found a reliable way to get a list of supported events,
  So i compiled some commons events in domEventsList. This should be enough i think.
  Since inline event are deprecated for a long time now. There is no need for more I think.

  This is more like a patch to fix conceptions flaws.

Please note that as said here https://github.com/kartik-v/bootstrap-fileinput/issues/1565#issuecomment-636308276 some info could be added to the documentation.

## Related Issues
If this is related to an existing ticket, include a link to it as well.
#1565
https://bugzilla.mozilla.org/show_bug.cgi?id=1582115

### CODE REVIEW

**Comment by kartik-v** [comment]
Thanks - I am optimizing this a bit and will update.

**Comment by kartik-v** [comment]
@Kwaadpepper thanks - have enhanced your PR and fixed a bit of minor issues in the inline event parsing and added a few function utilities for easier use. Please have a relook if anything amiss in your tests and let know.

**Comment by Kwaadpepper** [comment]
Thank you,  it looks to be working fine on my end

I'm curious why ```CSP_ATTRIB: 'data-csp-01928735'``` ? If you wanted to randomize the attr name you could you uniqId function ? I am also curious, why should this attribute name be randomized ?

**Comment by kartik-v** [comment]
> Thank you, it looks to be working fine on my end
> 
> I'm curious why `CSP_ATTRIB: 'data-csp-01928735'` ? If you wanted to randomize the attr name you could you uniqId function ? I am also curious, why should this attribute name be randomized ?

Just to ensure we do not have a similar naming attribute conflict being injected by the developer as part of his/her code. Its a constant attribute name but named such that it is highly unlikely to conflict.

**Comment by Kwaadpepper** [comment]
Ok, thanks  for the explanation.

**Comment by kw-pr** [comment]
Now it is triggering eval CSP because of `Function()`.
I am afraid this made things worse.

I actually was using `script-src 'self';` before this patch and it was working.

If you want to fix plugin templates I think this is not the place.
You should fix the plugin or use [unsafe-hashes](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#unsafe-hashes) as a workaround.

**Comment by Kwaadpepper** [comment]
I am using this on my project 

**Content-Security-Policy**

    default-src  'self' data: blob: 'nonce-Uv96RimOSuoCMSJU'
    script-src  resource://pdf.js/ 'nonce-Uv96RimOSuoCMSJU'
    style-src 'self'  'nonce-Uv96RimOSuoCMSJU'
    frame-src 'self' https://docs.google.com
    object-src 'self' blob:; base-uri 'self' resource://pdf.js/web/
    media-src 'self' blob:; report-uri /omenfilemanager/csp/report

I am not using unsafe-eval and i have no CSP errors (on Firefox), could you provide an example ?

**Comment by kw-pr** [comment]
I created an issue #1612 with more details. There is also an [example](https://pastebin.com/jza0mBfd).

See [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#Unsafe_eval_expressions) about `unsafe-eval` und `Function()`.

I came to this issue because my problem was introduced in [aa99882](https://github.com/kartik-v/bootstrap-fileinput/commit/aa998828a5b9779ef05ea2b17d6daa284b39f4f7).

**Comment by Kwaadpepper** [comment]
Ok I can understand this now. I will try to work on something when I have some time.

**Comment by kw-pr** [comment]
I would propose to remove the `domElementEvents` part of aa99882. `domElementsStyles` looks fine to me.

**Comment by Kwaadpepper** [comment]
I think you may be right. I can't think of a workaround. And if there were one I think it would be a security hole in the CSP system.

You could propose a PR if you have time.

**Pull request closed without merging**
