### PR TITLE
function callback success upload

### PR DESCRIPTION
**Pull request by jselamy**
Ajax request with HTTPSTATUS.NO_CONTENT the data is undefined therefore crashes when triying to access data.errorKeys

### CODE REVIEW

**Comment by kartik-v** [comment]
You need to modify JS code at your end... to validate and access errorKeys only if data is defined. For example:

```js
var errorKeys = data && data.errorKeys ? data.errorKeys : '';
```

**Comment by jselamy** [comment]
Ok it. But where at my end in the JS code ? 

Maybe i'm not getting something right.

Thx for the reply

**Comment by kartik-v** [comment]
Wherever you are reading data.errorKeys

**Comment by kartik-v** [comment]
Ok I understand this... will address this through a fix.

**Pull request closed without merging**
